# simplifed version of the upstream travis configuration.
# it runs acceptance test for different consensus like raft, istanbul and clique in parallel .

language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false

env:
    global:
      - TESSERA_JAR="$HOME/tessera.jar"

cache:
  directories:
    - $HOME/.m2

before_install:
    - git clone https://github.com/amalrajmani/quorum-acceptance-tests.git $TRAVIS_HOME/quorum-acceptance-tests
    - sudo chmod 755 $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh
    - sudo chmod 755 $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh

matrix:
  include:
    - name: linux-raft
      os: linux
      dist: trusty
      sudo: true
      go: 1.9.x
      env:
        - TF_VAR_consensus_mechanism=raft
        - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}

      addons:
      apt:
        update: true
        sources:
        - sourceline: ppa:ethereum/ethereum
        - sourceline: ppa:openjdk-r/ppa
        packages:
        - openjdk-8-jdk
        - dpkg # fixes issue with dpkg-deb error due to travis image issue
        - openssh-client
        - dnsutils
        - maven
        - solc
        - jq
        - curl

      install: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh raft

      script: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh raft


    - name: linux-istanbul
      os: linux
      dist: trusty
      sudo: true
      go: 1.9.x
      env:
      - TF_VAR_consensus_mechanism=istanbul
      - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}

      addons:
      apt:
        update: true
        sources:
        - sourceline: ppa:ethereum/ethereum
        - sourceline: ppa:openjdk-r/ppa
        packages:
        - openjdk-8-jdk
        - dpkg # fixes issue with dpkg-deb error due to travis image issue
        - openssh-client
        - dnsutils
        - maven
        - solc
        - jq
        - curl

      install: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh istanbul

      script: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh istanbul

    - name: linux-clique
      os: linux
      dist: trusty
      sudo: true
      go: 1.9.x
      env:
      - TF_VAR_consensus_mechanism=clique
      - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}

      addons:
      apt:
        update: true
        sources:
        - sourceline: ppa:ethereum/ethereum
        - sourceline: ppa:openjdk-r/ppa
        packages:
        - openjdk-8-jdk
        - dpkg # fixes issue with dpkg-deb error due to travis image issue
        - openssh-client
        - dnsutils
        - maven
        - solc
        - jq
        - curl

      install: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/install-linux.sh clique

      script: $TRAVIS_HOME/quorum-acceptance-tests/src/travis/script-linux.sh clique

    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      script:
      - sudo modprobe fuse
      - sudo chmod 666 /dev/fuse
      - sudo chown root:$USER /etc/fuse.conf
      - go run build/ci.go install
      - go run build/ci.go test -coverage $TEST_PACKAGES


    - os: osx
      osx_image: xcode9.2 # so we don't have to deal with Kernel Extension Consent UI which is never possible in CI
      go: 1.9.x
      sudo: required
      script:
        - brew update
        - brew install caskroom/cask/brew-cask
        - brew cask install osxfuse
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

